name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main

    - name: Install Azure ML extension
      run: az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v1.7
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Submit Azure ML job
      run: |
        az ml job create --file azureml-job.yaml \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --workspace-name ${{ secrets.AZURE_ML_WORKSPACE }} \
          --set \
            command="pip install scikit-learn && python train.py --training_data ${{ secrets.AZURE_TRAINING_DATA }} --reg_rate 0.01" \
            compute_target="Serverless" \
            environment="AzureML-ACPT-pytorch-1.13-py38-cuda11.7-gpu:10" \
            inputs.test="azureml:azureml_green_ball_ltc57xbpw2_input_data_test:1"

