name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch: # This enables manual triggering of the workflow

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
      
    - name: Install Azure CLI
      run: az extension add -n ml -y
      
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    
    - name: Submit Azure ML job
      run: |
        az ml job create --file azureml-job.yaml

        # Alternatively, you can inline the job submission command
        az ml job create --file azureml-job.yaml --set \
          command="pip install scikit-learn && python train.py --training_data ${{inputs.test}} --reg_rate 0.01" \
          compute_target="Serverless" \
          environment="AzureML-ACPT-pytorch-1.13-py38-cuda11.7-gpu:10" \
          inputs.test="azureml:azureml_green_ball_ltc57xbpw2_input_data_test:1"

      env:
        AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
        AZURE_RESOURCE_GROUP: ${{secrets.AZURE_RESOURCE_GROUP}}
        AZURE_ML_WORKSPACE: ${{secrets.AZURE_ML_WORKSPACE}}
